#pragma kernel ColorSeparatorInitialize
#pragma kernel ColorSeparatorMain

Texture2D<float4> InputTexture;
RWBuffer<uint> OutputBuffer;

[numthreads(64, 1, 1)]
void ColorSeparatorInitialize(uint3 id : SV_DispatchThreadID)
{
	OutputBuffer[id.x] = 0;
}

[numthreads(8, 8, 1)]	
void ColorSeparatorMain(uint3 id : SV_DispatchThreadID)
{
	float4 col = InputTexture[id.xy];
	uint sum = floor(col.r * 255.0) + floor(col.g * 255.0) + floor(col.b * 255.0);

	InterlockedAdd(OutputBuffer[sum], 1);
}